apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kube-logging
  name: elastic-data-pvc
  labels:
    app: elasticsearch
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G