apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-logging-pv-claim
  labels:
    app: elasticsearch
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi