kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kube-logging
  name: kube-logging-role
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]